# TODO 추후 kakaologin dev 검증 시 아래 yml 설정 변경할것
app:
  baseUrl: http://localhost:8080

spring:
  datasource:
    # local용 임시 db.
    url: jdbc:mysql://localhost:3306/mm
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/chatdb

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(jtFSE8X3pgeKaeyOGatxdqrvK1t4FmdbpZaHiPf6E2RoEiEEYdOQcvD3Ko34rAH9)
            client-secret: ENC(DuxDV+plHXpQS6l4tBhROg7UthSrsjKKlKgFlQijPxeSof6VLLaZBrcK7zdTydS4)
            redirect-uri: ${baseUrl}/oauth/callback/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  access_secret: ENC(JxVNEnrDkmH9HUSpiBjDD7GvObaGAWk21JXFvZPV4FgEmUQb/9LtEwkLjtTc5Q9F+WQj/gz5vGmPiP4H4BAAgw==)
  refresh_secret: ENC(hzfWfJcKzqgetp0MJkmjjOj5t9BwEsHjTV9i/t0iili1Cihv9K4LLAPtcR3ZSF8X+Bqmw3K2yAece+I1wHfXsA==)

# 적절하게 개발 시 DEBUG, TRACE 등으로 변경하여 사용
logging:
  level:
    root: info
websocket:
  allowedOrigins: "localhost:3000"
firebase:
  path: ENC(M47HHStR+hGcCyYNQ6hnGJ9IMadcBEmoLtXG+sYnGxs=)